services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend_1
            - backend_2
        restart: always

    backend_1:
        build: ./backend_1
        expose:
            - "5001"
        ports:
            - "5001:5001"
        environment:
            - PORT=5001
            - HOST=0.0.0.0
            - DEBUG=false
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DB=baer_aml
            - POSTGRES_USER=baer_aml
            - POSTGRES_PASSWORD=baer_aml
            - GROQ_API_KEY=${GROQ_API_KEY}
            - GROQ_API_BASE=${GROQ_API_BASE}
        env_file:
            - .env
        depends_on:
            - db
        restart: always

    backend_2:
        build: ./backend_2
        expose:
            - "5002"
        environment:
            - PORT=5002
            - HOST=0.0.0.0
            - DEBUG=false
            - PYTHONUNBUFFERED=1
            - GROQ_API_KEY=${GROQ_API_KEY} # From .env file
        restart: always

    frontend:
        build: ./frontend
        expose:
            - "3000"
        environment:
            - WATCHPACK_POLLING=true
            - WDS_SOCKET_PORT=0
            - NEXT_PUBLIC_API_URL=/api
            - NEXT_PUBLIC_LLM_API_URL=/llm-api
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next
        depends_on:
            - backend_1
            - backend_2
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
      
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        POSTGRES_DB: baer_aml
        POSTGRES_USER: baer_aml
        POSTGRES_PASSWORD: baer_aml
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data:
